# Generated by Django 5.2.4 on 2025-07-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=200)),
                ('Roll_Number', models.IntegerField()),
                ('Department', models.CharField(max_length=120)),
                ('Date_of_Birth', models.DateField()),
            ],
        ),
    ]
