# Generated by Django 5.2.4 on 2025-07-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=120)),
                ('Password', models.CharField(max_length=120)),
            ],
        ),
    ]
